version: 1.0.{build}

image: Visual Studio 2017

platform: x64

branches:
  only:
    - master

init:
  - set PATH="C:\\Python37";"C:\\Python37\Scripts";%PATH%

configuration:
  - Debug
  - Release

before_build:
  - cmake . -G"Visual Studio 15 2017"

build:
  project: ALL_BUILD.vcxproj
  verbosity: minimal

before_test:
- cmd: >-
    python -m pip install pytest pytest-xdist

    mkdir %APPVEYOR_BUILD_FOLDER%\test-results\pytest

test_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    python -m pytest --verbose --numprocesses=auto --junitxml=test-results\pytest\results.xml

after_test:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results\pytest\results.xml))
